// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD946vnw8S3Ox6HcLhQHxDi_7xGDHx9Xs',
    appId: '1:943989389663:android:92151a48d82274ec909eea',
    messagingSenderId: '943989389663',
    projectId: 'fir-codelab-1ee19',
    storageBucket: 'fir-codelab-1ee19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh-Fr0IRGrB7getAPiBcug6QI5dhpFaxE',
    appId: '1:943989389663:ios:04b8d6aa4121814c909eea',
    messagingSenderId: '943989389663',
    projectId: 'fir-codelab-1ee19',
    storageBucket: 'fir-codelab-1ee19.appspot.com',
    iosClientId: '943989389663-e0vr7hjj1h5m5il0qv5aklpo80kpi46b.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh-Fr0IRGrB7getAPiBcug6QI5dhpFaxE',
    appId: '1:943989389663:ios:04b8d6aa4121814c909eea',
    messagingSenderId: '943989389663',
    projectId: 'fir-codelab-1ee19',
    storageBucket: 'fir-codelab-1ee19.appspot.com',
    iosClientId: '943989389663-e0vr7hjj1h5m5il0qv5aklpo80kpi46b.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
